INSERT INTO users (name, age) VALUES ("Peter", 26);
INSERT INTO users (name, age) VALUES ("Joe", 30);
INSERT INTO users (name, age) VALUES ("Josiah", 17);
INSERT INTO users (name, age) VALUES ("Isaac", 18);
INSERT INTO users (name, age) VALUES ("Caleb", 24);
INSERT INTO users (name, age) VALUES ("Delaney", 28);
INSERT INTO users (name, age) VALUES ("Nathan", 29);
INSERT INTO users (name, age) VALUES ("Ben", 27);
INSERT INTO users (name, age) VALUES ("Alessa", 25);
INSERT INTO users (name, age) VALUES ("Trevor", 26);
INSERT INTO users (name, age) VALUES ("Kathleen", 26);
INSERT INTO users (name, age) VALUES ("Jacon", 31);
INSERT INTO users (name, age) VALUES ("Skyler", 21);
INSERT INTO users (name, age) VALUES ("Esther", 21);
INSERT INTO users (name, age) VALUES ("Joshua", 35);
INSERT INTO users (name, age) VALUES ("Scott", 52);
INSERT INTO users (name, age) VALUES ("Lisa", 54);
INSERT INTO users (name, age) VALUES ("Peter", 26);
INSERT INTO users (name, age) VALUES ("Jason", 28);
INSERT INTO users (name, age) VALUES ("Jessie", 26);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Switch for Nick", "Personal", 350, "January 1, 2020", "December 31, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Money for Luke", "Personal", 1000, "September 20, 2020", "October 21, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help for Covid", "Business", 15000, "Febuary 2, 2020", "September 9, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food for Squarespace", "Business", 20000, "March 1, 2020", "October 31, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food for America", "Personal", 10000000, "January 1, 2020", "December 31, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Universal language of Music", "Education", 300000, "March 15, 2020", "January 31, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Send Roger Bradford to Collage", "Education", 50000, "June 3, 2020", "November 23, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help for Brooklyn", "Business", 1000000, "March 22 1, 2020", "July 4, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Holloween Party", "Personal", 1000, "January 1, 2020", "October 25, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Xmas for kids", "Personal", 2500, "January 1, 2020", "December 1, 2020");

INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (69, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 13, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 14, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 15, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (69, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 13, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 14, 8);
